---
wheel_width: 0.011 # Thickness of the wheel
wheel_radius: 0.033 # radius of the two differential wheels. 
                  # The radius of the castor wheel is half of this
wheel_base: 0.16   # Distance between the wheel centers
chasis_length: 0.178 # Length of the robot's body
chasis_thickness: 0.140 # z dimension of the robot body
encoder_ticks_per_rev: 4096  #Number of ticks for completing one complete cycle of revolution # clarify once
max_trans_vel: 0.22 # Maximum linear velocity of the robot
max_rot_vel_robot: 2.84 # Maximum rotational velocity of the robot
max_rot_vel_motor: 6.35492 # Maximum rotational velocity of the motor
max_motor_power: 260
max_wheel_command: 265
wheel_axle_offset: 0.02
turtle_bot_weight: 1.0
wheel_weight: 0.03


